export const CarBrands = [
  {
    name: "Suzuki",
    link: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9.jpeg",
    imgAlt: "Maruti Suzuki",
  },
  {
    name: "Hyundai",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7.jpeg",
    imgAlt: "Hyundai",
  },
  {
    name: "Honda",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-6.jpeg",
    imgAlt: "Honda",
  },
  {
    name: "Tata",
    link: "https://gomechanic.in/madurai/car-ac-repair/tata",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-14.jpeg",
    imgAlt: "Tata",
  },
  {
    name: "Ford",
    link: "https://gomechanic.in/madurai/car-ac-repair/ford",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-5.jpeg",
    imgAlt: "Ford",
  },
  {
    name: "Volkswagen",
    link: "https://gomechanic.in/madurai/car-ac-repair/volkswagen",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-16.jpeg",
    imgAlt: "Volkswagen",
  },
  {
    name: "Mahindra",
    link: "https://gomechanic.in/madurai/car-ac-repair/mahindra",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-8.jpeg",
    imgAlt: "Mahindra",
  },
  {
    name: "Chevrolet",
    link: "https://gomechanic.in/madurai/car-ac-repair/chevrolet",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-1.jpeg",
    imgAlt: "Chevrolet",
  },
  {
    name: "Toyota",
    link: "https://gomechanic.in/madurai/car-ac-repair/toyota",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-15.jpeg",
    imgAlt: "Toyota",
  },
  {
    name: "Skoda",
    link: "https://gomechanic.in/madurai/car-ac-repair/skoda",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-13.jpeg",
    imgAlt: "Skoda",
  },
  {
    name: "Nissan",
    link: "https://gomechanic.in/madurai/car-ac-repair/nissan",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-11.jpeg",
    imgAlt: "Nissan",
  },
  {
    name: "Fiat",
    link: "https://gomechanic.in/madurai/car-ac-repair/fiat",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-4.jpeg",
    imgAlt: "Fiat",
  },
  {
    name: "BMW",
    link: "https://gomechanic.in/madurai/car-ac-repair/bmw",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-20.jpeg",
    imgAlt: "BMW",
  },
  {
    name: "Audi",
    link: "https://gomechanic.in/madurai/car-ac-repair/audi",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-18.jpeg",
    imgAlt: "Audi",
  },
  {
    name: "Mercedes",
    link: "https://gomechanic.in/madurai/car-ac-repair/mercedes",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-26.jpeg",
    imgAlt: "Mercedes",
  },
  {
    name: "Jeep",
    link: "https://gomechanic.in/madurai/car-ac-repair/jeep",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-34.jpeg",
    imgAlt: "Jeep",
  },
  {
    name: "Mitsubishi",
    link: "https://gomechanic.in/madurai/car-ac-repair/mitsubishi",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-10.jpeg",
    imgAlt: "Mitsubishi",
  },
  {
    name: "MG",
    link: "https://gomechanic.in/madurai/car-ac-repair/mg",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-37.jpeg",
    imgAlt: "MG",
  },
  {
    name: "Land Rover",
    link: "https://gomechanic.in/madurai/car-ac-repair/land-rover",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-24.jpeg",
    imgAlt: "Land Rover",
  },
  {
    name: "Volvo",
    link: "https://gomechanic.in/madurai/car-ac-repair/volvo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-30.jpeg",
    imgAlt: "Volvo",
  },
  {
    name: "Jaguar",
    link: "https://gomechanic.in/madurai/car-ac-repair/jaguar",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-22.jpeg",
    imgAlt: "Jaguar",
  },
  {
    name: "Ssangyong",
    link: "https://gomechanic.in/madurai/car-ac-repair/ssangyong",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-36.jpeg",
    imgAlt: "Ssangyong",
  },
  {
    name: "Isuzu",
    link: "https://gomechanic.in/madurai/car-ac-repair/isuzu",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-32.jpeg",
    imgAlt: "Isuzu",
  },
  {
    name: "Mini",
    link: "https://gomechanic.in/madurai/car-ac-repair/mini",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-27.jpeg",
    imgAlt: "Mini",
  },
  {
    name: "Force",
    link: "https://gomechanic.in/madurai/car-ac-repair/force",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-31.jpeg",
    imgAlt: "Force",
  },
  {
    name: "Opel",
    link: "https://gomechanic.in/madurai/car-ac-repair/opel",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-35.jpeg",
    imgAlt: "Opel",
  },
  {
    name: "Porsche",
    link: "https://gomechanic.in/madurai/car-ac-repair/porsche",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-28.jpeg",
    imgAlt: "Porsche",
  },
  {
    name: "Daewoo",
    link: "https://gomechanic.in/madurai/car-ac-repair/daewoo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-2.jpeg",
    imgAlt: "Daewoo",
  },
  {
    name: "Peugeot",
    link: "https://gomechanic.in/madurai/car-ac-repair/peugeot",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-29.jpeg",
    imgAlt: "Peugeot",
  },
  {
    name: "Lexus",
    link: "https://gomechanic.in/madurai/car-ac-repair/lexus",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-25.jpeg",
    imgAlt: "Lexus",
  },
  {
    name: "Ambassador",
    link: "https://gomechanic.in/madurai/car-ac-repair/ambassador",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-19.jpeg",
    imgAlt: "Ambassador",
  },
  {
    name: "Aston Martin",
    link: "https://gomechanic.in/madurai/car-ac-repair/aston-martin",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-21.jpeg",
    imgAlt: "Aston Martin",
  },
  {
    name: "Ferrari",
    link: "https://gomechanic.in/madurai/car-ac-repair/ferrari",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-23.jpeg",
    imgAlt: "Ferrari",
  },
  {
    name: "Maserati",
    link: "https://gomechanic.in/madurai/car-ac-repair/maserati",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-33.jpeg",
    imgAlt: "Maserati",
  },
];

export const Suzuki = [
  {
    name: "Swift",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-swift",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-240.jpeg",
  },
  {
    name: "WagonR",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-wagonr",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-251.jpeg",
  },
  {
    name: "Swift Dzire",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-swift-dzire",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-243.jpeg",
  },
  {
    name: "Baleno",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-baleno",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-205.jpeg",
  },
  {
    name: "Alto",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-alto",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-197.jpeg",
  },
  {
    name: "Ritz",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-ritz",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-234.jpeg",
  },
  {
    name: "Celerio",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-celerio",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-208.jpeg",
  },
  {
    name: "Ciaz",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-ciaz",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-211.jpeg",
  },
  {
    name: "Alto K10",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-alto-k10",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-201.jpeg",
  },
  {
    name: "Ertiga",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-ertiga",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-216.jpeg",
  },
  {
    name: "Alto 800",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-alto-800",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-199.jpeg",
  },
  {
    name: "Vitara Brezza",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-vitara-brezza",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-481.jpeg",
  },
  {
    name: "Estilo",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-estilo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-221.jpeg",
  },
  {
    name: "SX4",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-sx4",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-246.jpeg",
  },
  {
    name: "800",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-800",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-195.jpeg",
  },
  {
    name: "Zen",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-zen",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-253.jpeg",
  },
  {
    name: "A-Star",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-a-star",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-203.jpeg",
  },
  {
    name: "Ignis",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-ignis",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-482.jpeg",
  },
  {
    name: "S-Cross",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-s-cross",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-237.jpeg",
  },
  {
    name: "Eeco",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-eeco",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-214.jpeg",
  },
  {
    name: "Esteem",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-esteem",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-219.jpeg",
  },
  {
    name: "Omni",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-omni",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-232.jpeg",
  },
  {
    name: "S-Presso",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-s-presso",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-532.jpeg",
  },
  {
    name: "Grand Vitara",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-grand-vitara",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-223.jpeg",
  },
  {
    name: "Gypsy",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-gypsy",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-226.jpeg",
  },
  {
    name: "Kizashi",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-kizashi",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-229.jpeg",
  },
  {
    name: "Versa",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-versa",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-249.jpeg",
  },
  {
    name: "XL6",
    href: "https://gomechanic.in/madurai/car-ac-repair/maruti-suzuki-xl6",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-9-model-550.jpeg",
  },
];

export const Hyundai = [
  {
    name: "i10",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-i10",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-152.jpeg",
  },
  {
    name: "i20",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-i20",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-154.jpeg",
  },
  {
    name: "Grand i10",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-grand-i10",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-149.jpeg",
  },
  {
    name: "Santro Xing",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-santro-xing",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-162.jpeg",
  },
  {
    name: "Eon",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-eon",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-144.jpeg",
  },
  {
    name: "Xcent",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-xcent",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-183.jpeg",
  },
  {
    name: "Elite i20",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-elite-i20",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-141.jpeg",
  },
  {
    name: "Creta",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-creta",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-135.jpeg",
  },
  {
    name: "Alcazar",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-alcazar",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-578.jpeg",
  },
  {
    name: "Verna Fluidic",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-verna-fluidic",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-177.jpeg",
  },
  {
    name: "Verna",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-verna",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-174.jpeg",
  },
  {
    name: "Accent",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-accent",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-129.jpeg",
  },
  {
    name: "Santro",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-santro",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-533.jpeg",
  },
  {
    name: "i20 Active",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-i20-active",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-157.jpeg",
  },
  {
    name: "Elantra",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-elantra",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-138.jpeg",
  },
  {
    name: "Getz",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-getz",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-146.jpeg",
  },
  {
    name: "Venue",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-venue",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-513.jpeg",
  },
  {
    name: "Grand i10 Nios",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-grand-i10-nios",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-534.jpeg",
  },
  {
    name: "Verna Transform",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-verna-transform",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-180.jpeg",
  },
  {
    name: "Getz Prime",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-getz-prime",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-148.jpeg",
  },
  {
    name: "Kona",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-kona",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-593.jpeg",
  },
  {
    name: "Accent Viva",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-accent-viva",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-132.jpeg",
  },
  {
    name: "SantaFE",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-santafe",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-160.jpeg",
  },
  {
    name: "Tucson",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-tucson",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-173.jpeg",
  },
  {
    name: "Sonata",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-sonata",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-164.jpeg",
  },
  {
    name: "Sonata Embera",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-sonata-embera",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-167.jpeg",
  },
  {
    name: "Aura",
    link: "https://gomechanic.in/madurai/car-ac-repair/hyundai-aura",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-7-model-535.jpeg",
  },
];

export const Honda = [
  {
    name: "City IVTEC",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-city-ivtec",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-6-model-115.jpeg",
    imgAlt: "City IVTEC",
  },
  {
    name: "Amaze",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-amaze",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-6-model-107.jpeg",
    imgAlt: "Amaze",
  },
  {
    name: "City",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-city",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-6-model-112.jpeg",
    imgAlt: "City",
  },
  {
    name: "Brio",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-brio",
    src: "/addons/2eb32392.png",
    imgAlt: "Brio",
  },
  {
    name: "Jazz",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-jazz",
    src: "/addons/2eb32392.png",
    imgAlt: "Jazz",
  },
  {
    name: "Civic",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-civic",
    src: "/addons/2eb32392.png",
    imgAlt: "Civic",
  },
  {
    name: "Accord",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-accord",
    src: "/addons/2eb32392.png",
    imgAlt: "Accord",
  },
  {
    name: "City ZX",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-city-zx",
    src: "/addons/2eb32392.png",
    imgAlt: "City ZX",
  },
  {
    name: "WRV",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-wrv",
    src: "/addons/2eb32392.png",
    imgAlt: "WRV",
  },
  {
    name: "Mobilio",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-mobilio",
    src: "/addons/2eb32392.png",
    imgAlt: "Mobilio",
  },
  {
    name: "City IDTEC",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-city-idtec",
    src: "/addons/2eb32392.png",
    imgAlt: "City IDTEC",
  },
  {
    name: "CRV",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-crv",
    src: "/addons/2eb32392.png",
    imgAlt: "CRV",
  },
  {
    name: "BRV",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-brv",
    src: "/addons/2eb32392.png",
    imgAlt: "BRV",
  },
  {
    name: "Accord Hybrid",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-accord-hybrid",
    src: "/addons/2eb32392.png",
    imgAlt: "Accord Hybrid",
  },
  {
    name: "Elevate",
    link: "https://gomechanic.in/madurai/car-ac-repair/honda-elevate",
    src: "/addons/2eb32392.png",
    imgAlt: "Elevate",
  },
];

export const Tata = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-tiago",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-14-model-484.jpeg",
    alt: "Tiago",
    name: "Tiago",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-tiago-nrg",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-14-model-581.jpeg",
    alt: "Tiago NRG",
    name: "Tiago NRG",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-nano",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-14-model-331.jpeg",
    alt: "Nano",
    name: "Nano",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-zest",
    src: "/addons/2eb32392.png",
    alt: "Zest",
    name: "Zest",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-nexon",
    src: "/addons/2eb32392.png",
    alt: "Nexon",
    name: "Nexon",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-indica-vista",
    src: "/addons/2eb32392.png",
    alt: "Indica Vista",
    name: "Indica Vista",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-tigor",
    src: "/addons/2eb32392.png",
    alt: "Tigor",
    name: "Tigor",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-manza",
    src: "/addons/2eb32392.png",
    alt: "Manza",
    name: "Manza",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-indica",
    src: "/addons/2eb32392.png",
    alt: "Indica",
    name: "Indica",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-indigo",
    src: "/addons/2eb32392.png",
    alt: "Indigo",
    name: "Indigo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-safari",
    src: "/addons/2eb32392.png",
    alt: "Safari",
    name: "Safari",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-indigo-ecs",
    src: "/addons/2eb32392.png",
    alt: "Indigo eCS",
    name: "Indigo eCS",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-indica-v2",
    src: "/addons/2eb32392.png",
    alt: "Indica V2",
    name: "Indica V2",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-bolt",
    src: "/addons/2eb32392.png",
    alt: "Bolt",
    name: "Bolt",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-indigo-cs",
    src: "/addons/2eb32392.png",
    alt: "Indigo CS",
    name: "Indigo CS",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-safari-storme",
    src: "/addons/2eb32392.png",
    alt: "Safari Storme",
    name: "Safari Storme",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-nano-genx",
    src: "/addons/2eb32392.png",
    alt: "Nano Genx",
    name: "Nano Genx",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-indica-ev2",
    src: "/addons/2eb32392.png",
    alt: "Indica eV2",
    name: "Indica eV2",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-altroz",
    src: "/addons/2eb32392.png",
    alt: "Altroz",
    name: "Altroz",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-aria",
    src: "/addons/2eb32392.png",
    alt: "Aria",
    name: "Aria",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-harrier",
    src: "/addons/2eb32392.png",
    alt: "Harrier",
    name: "Harrier",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-hexa",
    src: "/addons/2eb32392.png",
    alt: "Hexa",
    name: "Hexa",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-sumo-grande",
    src: "/addons/2eb32392.png",
    alt: "Sumo Grande",
    name: "Sumo Grande",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-indigo-marina",
    src: "/addons/2eb32392.png",
    alt: "Indigo Marina",
    name: "Indigo Marina",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-sumo-gold",
    src: "/addons/2eb32392.png",
    alt: "Sumo Gold",
    name: "Sumo Gold",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-sumo-grande-mk-ii",
    src: "/addons/2eb32392.png",
    alt: "Sumo Grande MK II",
    name: "Sumo Grande MK II",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-venture",
    src: "/addons/2eb32392.png",
    alt: "Venture",
    name: "Venture",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-indigo-xl",
    src: "/addons/2eb32392.png",
    alt: "Indigo XL",
    name: "Indigo XL",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-sumo-spacio",
    src: "/addons/2eb32392.png",
    alt: "Sumo Spacio",
    name: "Sumo Spacio",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-winger",
    src: "/addons/2eb32392.png",
    alt: "Winger",
    name: "Winger",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-xenon",
    src: "/addons/2eb32392.png",
    alt: "Xenon",
    name: "Xenon",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-sumo-victa",
    src: "/addons/2eb32392.png",
    alt: "Sumo Victa",
    name: "Sumo Victa",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/tata-punch",
    src: "/addons/2eb32392.png",
    alt: "Punch",
    name: "Punch",
  },
];

export const Ford = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-figo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-5-model-90.jpeg",
    alt: "Figo",
    name: "Figo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-eco-sport",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-5-model-77.jpeg",
    alt: "Eco Sport",
    name: "Eco Sport",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-figo-aspire",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-5-model-93.jpeg",
    alt: "Figo Aspire",
    name: "Figo Aspire",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-fiesta",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-5-model-84.jpeg",
    alt: "Fiesta",
    name: "Fiesta",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-fiesta-classic",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-5-model-87.jpeg",
    alt: "Fiesta Classic",
    name: "Fiesta Classic",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-ikon",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-5-model-99.jpeg",
    alt: "Ikon",
    name: "Ikon",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-endeavour",
    src: "/addons/2eb32392.png",
    alt: "Endeavour",
    name: "Endeavour",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-freestyle",
    src: "/addons/2eb32392.png",
    alt: "Freestyle",
    name: "Freestyle",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-fusion",
    src: "/addons/2eb32392.png",
    alt: "Fusion",
    name: "Fusion",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-escort",
    src: "/addons/2eb32392.png",
    alt: "Escort",
    name: "Escort",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-mondeo",
    src: "/addons/2eb32392.png",
    alt: "Mondeo",
    name: "Mondeo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/ford-mustang",
    src: "/addons/2eb32392.png",
    alt: "Mustang",
    name: "Mustang",
  },
];

export const Volkswagen = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-polo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-16-model-375.jpeg",
    alt: "Polo",
    name: "Polo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-vento",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-16-model-378.jpeg",
    alt: "Vento",
    name: "Vento",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-ameo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-16-model-490.jpeg",
    alt: "Ameo",
    name: "Ameo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-cross-polo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-16-model-366.jpeg",
    alt: "Cross Polo",
    name: "Cross Polo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-jetta",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-16-model-369.jpeg",
    alt: "Jetta",
    name: "Jetta",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-passat",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-16-model-372.jpeg",
    alt: "Passat",
    name: "Passat",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-taigun",
    src: "/addons/2eb32392.png",
    alt: "Taigun",
    name: "Taigun",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-t-roc",
    src: "/addons/2eb32392.png",
    alt: "T-Roc",
    name: "T-Roc",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-beetle",
    src: "/addons/2eb32392.png",
    alt: "Beetle",
    name: "Beetle",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-tiguan",
    src: "/addons/2eb32392.png",
    alt: "Tiguan",
    name: "Tiguan",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-virtus",
    src: "/addons/2eb32392.png",
    alt: "Virtus",
    name: "Virtus",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/volkswagen-phaeton",
    src: "/addons/2eb32392.png",
    alt: "Phaeton",
    name: "Phaeton",
  },
];

export const Mahindra = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-xuv-500",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-8-model-193.jpeg",
    alt: "XUV 500",
    name: "XUV 500",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-scorpio",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-8-model-188.jpeg",
    alt: "Scorpio",
    name: "Scorpio",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-kuv-100",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-8-model-479.jpeg",
    alt: "KUV 100",
    name: "KUV 100",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-xylo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-8-model-194.jpeg",
    alt: "Xylo",
    name: "Xylo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-tuv-300",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-8-model-381.jpeg",
    alt: "TUV 300",
    name: "TUV 300",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-bolero-neo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-8-model-576.jpeg",
    alt: "Bolero Neo",
    name: "Bolero Neo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-quanto",
    src: "/addons/2eb32392.png",
    alt: "Quanto",
    name: "Quanto",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-bolero",
    src: "/addons/2eb32392.png",
    alt: "Bolero",
    name: "Bolero",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-imperio-",
    src: "/addons/2eb32392.png",
    alt: "Imperio",
    name: "Imperio",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-logan",
    src: "/addons/2eb32392.png",
    alt: "Logan",
    name: "Logan",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-verito",
    src: "/addons/2eb32392.png",
    alt: "Verito",
    name: "Verito",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-xuv-300",
    src: "/addons/2eb32392.png",
    alt: "XUV 300",
    name: "XUV 300",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-thar",
    src: "/addons/2eb32392.png",
    alt: "Thar",
    name: "Thar",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-bolero-camper",
    src: "/addons/2eb32392.png",
    alt: "Bolero Camper",
    name: "Bolero Camper",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-nuvosport",
    src: "/addons/2eb32392.png",
    alt: "NuvoSport",
    name: "NuvoSport",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-marazzo",
    src: "/addons/2eb32392.png",
    alt: "Marazzo",
    name: "Marazzo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-xuv-700",
    src: "/addons/2eb32392.png",
    alt: "XUV 700",
    name: "XUV 700",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-verito-vibe-cs",
    src: "/addons/2eb32392.png",
    alt: "Verito Vibe CS",
    name: "Verito Vibe CS",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-bolero-pickup",
    src: "/addons/2eb32392.png",
    alt: "Bolero Pickup",
    name: "Bolero Pickup",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-scorpio-getaway",
    src: "/addons/2eb32392.png",
    alt: "Scorpio Getaway",
    name: "Scorpio Getaway",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-alturas-g4",
    src: "/addons/2eb32392.png",
    alt: "Alturas G4",
    name: "Alturas G4",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-e20-plus",
    src: "/addons/2eb32392.png",
    alt: "E20 Plus",
    name: "E20 Plus",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-tuv-300-plus",
    src: "/addons/2eb32392.png",
    alt: "TUV 300 Plus",
    name: "TUV 300 Plus",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-scorpio-n",
    src: "/addons/2eb32392.png",
    alt: "Scorpio N",
    name: "Scorpio N",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mahindra-reva",
    src: "/addons/2eb32392.png",
    alt: "Reva",
    name: "Reva",
  },
];

export const Chevrolet = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-beat",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-1-model-4.jpeg",
    alt: "Beat",
    name: "Beat",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-spark",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-1-model-31.jpeg",
    alt: "Spark",
    name: "Spark",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-cruze",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-1-model-8.jpeg",
    alt: "Cruze",
    name: "Cruze",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-aveo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-1-model-1.jpeg",
    alt: "Aveo",
    name: "Aveo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-sail",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-1-model-25.jpeg",
    alt: "Sail",
    name: "Sail",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-enjoy",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-1-model-11.jpeg",
    alt: "Enjoy",
    name: "Enjoy",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-uva",
    src: "/addons/2eb32392.png",
    alt: "UVA",
    name: "UVA",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-optra",
    src: "/addons/2eb32392.png",
    alt: "Optra",
    name: "Optra",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-sail-hatchback",
    src: "/addons/2eb32392.png",
    alt: "Sail Hatchback",
    name: "Sail Hatchback",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-optra-magnum",
    src: "/addons/2eb32392.png",
    alt: "Optra Magnum",
    name: "Optra Magnum",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-tavera",
    src: "/addons/2eb32392.png",
    alt: "Tavera",
    name: "Tavera",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-optra-srv",
    src: "/addons/2eb32392.png",
    alt: "Optra SRV",
    name: "Optra SRV",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-captiva",
    src: "/addons/2eb32392.png",
    alt: "Captiva",
    name: "Captiva",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-forester",
    src: "/addons/2eb32392.png",
    alt: "Forester",
    name: "Forester",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/chevrolet-trailblazer",
    src: "/addons/2eb32392.png",
    alt: "Trailblazer",
    name: "Trailblazer",
  },
];

export const Toyota = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-sera",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-15-model-564.jpeg",
    alt: "Sera",
    name: "Sera",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-etios",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-15-model-353.jpeg",
    alt: "Etios",
    name: "Etios",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-innova",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-15-model-363.jpeg",
    alt: "Innova",
    name: "Innova",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-corolla-altis",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-15-model-350.jpeg",
    alt: "Corolla Altis",
    name: "Corolla Altis",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-etios-liva",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-15-model-359.jpeg",
    alt: "Etios Liva",
    name: "Etios Liva",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-fortuner",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-15-model-362.jpeg",
    alt: "Fortuner",
    name: "Fortuner",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-hilux",
    src: "/addons/2eb32392.png",
    alt: "Hilux",
    name: "Hilux",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-innova-crysta",
    src: "/addons/2eb32392.png",
    alt: "Innova Crysta",
    name: "Innova Crysta",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-corolla",
    src: "/addons/2eb32392.png",
    alt: "Corolla",
    name: "Corolla",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-qualis",
    src: "/addons/2eb32392.png",
    alt: "Qualis",
    name: "Qualis",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-etios-cross",
    src: "/addons/2eb32392.png",
    alt: "Etios Cross",
    name: "Etios Cross",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-yaris",
    src: "/addons/2eb32392.png",
    alt: "Yaris",
    name: "Yaris",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-camry",
    src: "/addons/2eb32392.png",
    alt: "Camry",
    name: "Camry",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-glanza",
    src: "/addons/2eb32392.png",
    alt: "Glanza",
    name: "Glanza",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-land-cruiser",
    src: "/addons/2eb32392.png",
    alt: "Land Cruiser",
    name: "Land Cruiser",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-land-cruiser-prado",
    src: "/addons/2eb32392.png",
    alt: "Land Cruiser Prado",
    name: "Land Cruiser Prado",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-urban-cruiser",
    src: "/addons/2eb32392.png",
    alt: "Urban Cruiser",
    name: "Urban Cruiser",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-alphard",
    src: "/addons/2eb32392.png",
    alt: "Alphard",
    name: "Alphard",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-vellfire",
    src: "/addons/2eb32392.png",
    alt: "Vellfire",
    name: "Vellfire",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-urban-cruiser-hyryder",
    src: "/addons/2eb32392.png",
    alt: "Urban Cruiser Hyryder",
    name: "Urban Cruiser Hyryder",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/toyota-innova-hycross",
    src: "/addons/2eb32392.png",
    alt: "Innova Hycross",
    name: "Innova Hycross",
  },
];

export const Skoda = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-rapid",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-13-model-288.jpeg",
    alt: "Rapid",
    name: "Rapid",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-fabia",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-13-model-278.jpeg",
    alt: "Fabia",
    name: "Fabia",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-superb",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-13-model-291.jpeg",
    alt: "Superb",
    name: "Superb",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-laura",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-13-model-284.jpeg",
    alt: "Laura",
    name: "Laura",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-octavia",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-13-model-285.jpeg",
    alt: "Octavia",
    name: "Octavia",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-yeti",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-13-model-294.jpeg",
    alt: "Yeti",
    name: "Yeti",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-fabia-scout",
    src: "/addons/2eb32392.png",
    alt: "Fabia Scout",
    name: "Fabia Scout",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-kodiaq",
    src: "/addons/2eb32392.png",
    alt: "Kodiaq",
    name: "Kodiaq",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-kushaq",
    src: "/addons/2eb32392.png",
    alt: "Kushaq",
    name: "Kushaq",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/skoda-slavia",
    src: "/addons/2eb32392.png",
    alt: "Slavia",
    name: "Slavia",
  },
];

export const Nissan = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-micra",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-11-model-258.jpeg",
    alt: "Micra",
    name: "Micra",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-sunny",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-11-model-262.jpeg",
    alt: "Sunny",
    name: "Sunny",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-terrano",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-11-model-264.jpeg",
    alt: "Terrano",
    name: "Terrano",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-micra-active",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-11-model-260.jpeg",
    alt: "Micra Active",
    name: "Micra Active",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-teana",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-11-model-263.jpeg",
    alt: "Teana",
    name: "Teana",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-kicks",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-11-model-552.jpeg",
    alt: "Kicks",
    name: "Kicks",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-evalia",
    src: "/addons/2eb32392.png",
    alt: "Evalia",
    name: "Evalia",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-x-trail",
    src: "/addons/2eb32392.png",
    alt: "X-Trail",
    name: "X-Trail",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-gtr",
    src: "/addons/2eb32392.png",
    alt: "GTR",
    name: "GTR",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/nissan-magnite",
    src: "/addons/2eb32392.png",
    alt: "Magnite",
    name: "Magnite",
  },
];

export const Fiat = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-punto",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-4-model-71.jpeg",
    alt: "Punto",
    name: "Punto",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-linea",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-4-model-53.jpeg",
    alt: "Linea",
    name: "Linea",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-punto-evo",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-4-model-74.jpeg",
    alt: "Punto Evo",
    name: "Punto Evo",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-palio-d",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-4-model-59.jpeg",
    alt: "Palio D",
    name: "Palio D",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-avventura",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-4-model-50.jpeg",
    alt: "Avventura",
    name: "Avventura",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-palio-stile",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-4-model-65.jpeg",
    alt: "Palio Stile",
    name: "Palio Stile",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-linea-classic",
    src: "/addons/2eb32392.png",
    alt: "Linea Classic",
    name: "Linea Classic",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-adventure",
    src: "/addons/2eb32392.png",
    alt: "Adventure",
    name: "Adventure",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-palio-nv",
    src: "/addons/2eb32392.png",
    alt: "Palio NV",
    name: "Palio NV",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-abarth-punto",
    src: "/addons/2eb32392.png",
    alt: "Abarth Punto",
    name: "Abarth Punto",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-urban-cross",
    src: "/addons/2eb32392.png",
    alt: "Urban Cross",
    name: "Urban Cross",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-uno",
    src: "/addons/2eb32392.png",
    alt: "Uno",
    name: "Uno",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/fiat-petra",
    src: "/addons/2eb32392.png",
    alt: "Petra",
    name: "Petra",
  },
];

export const Bmw = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-x1",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-20-model-410.jpeg",
    alt: "X1",
    name: "X1",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-3-series",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-20-model-402.jpeg",
    alt: "3 Series",
    name: "3 Series",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-2-series",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-20-model-566.jpeg",
    alt: "2 Series",
    name: "2 Series",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-5-series",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-20-model-404.jpeg",
    alt: "5 Series",
    name: "5 Series",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-3-series-gt",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-20-model-403.jpeg",
    alt: "3 Series GT",
    name: "3 Series GT",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-x3",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-20-model-411.jpeg",
    alt: "X3",
    name: "X3",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-7-series",
    src: "/addons/2eb32392.png",
    alt: "7 Series",
    name: "7 Series",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-1-series",
    src: "/addons/2eb32392.png",
    alt: "1 Series",
    name: "1 Series",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-z4",
    src: "/addons/2eb32392.png",
    alt: "Z4",
    name: "Z4",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-5-series-gt",
    src: "/addons/2eb32392.png",
    alt: "5 Series GT",
    name: "5 Series GT",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-x5",
    src: "/addons/2eb32392.png",
    alt: "X5",
    name: "X5",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-x6",
    src: "/addons/2eb32392.png",
    alt: "X6",
    name: "X6",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-6-series",
    src: "/addons/2eb32392.png",
    alt: "6 Series",
    name: "6 Series",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-m5",
    src: "/addons/2eb32392.png",
    alt: "M5",
    name: "M5",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-m3",
    src: "/addons/2eb32392.png",
    alt: "M3",
    name: "M3",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-x4",
    src: "/addons/2eb32392.png",
    alt: "X4",
    name: "X4",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-6-series-gt",
    src: "/addons/2eb32392.png",
    alt: "6 Series GT",
    name: "6 Series GT",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-x7",
    src: "/addons/2eb32392.png",
    alt: "X7",
    name: "X7",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-i4",
    src: "/addons/2eb32392.png",
    alt: "i4",
    name: "i4",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/bmw-ix",
    src: "/addons/2eb32392.png",
    alt: "iX",
    name: "iX",
  },
];

export const Audi = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-a4",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-18-model-388.jpeg",
    alt: "A4",
    name: "A4",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-a6",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-18-model-389.jpeg",
    alt: "A6",
    name: "A6",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-q3",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-18-model-393.jpeg",
    alt: "Q3",
    name: "Q3",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-q2",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-18-model-565.jpeg",
    alt: "Q2",
    name: "Q2",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-q7",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-18-model-395.jpeg",
    alt: "Q7",
    name: "Q7",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-a3",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-18-model-387.jpeg",
    alt: "A3",
    name: "A3",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-q5",
    src: "/addons/2eb32392.png",
    alt: "Q5",
    name: "Q5",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-a8-l",
    src: "/addons/2eb32392.png",
    alt: "A8 L",
    name: "A8 L",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-s4",
    src: "/addons/2eb32392.png",
    alt: "S4",
    name: "S4",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-a5",
    src: "/addons/2eb32392.png",
    alt: "A5",
    name: "A5",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-a7",
    src: "/addons/2eb32392.png",
    alt: "A7",
    name: "A7",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-a8",
    src: "/addons/2eb32392.png",
    alt: "A8",
    name: "A8",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-tt",
    src: "/addons/2eb32392.png",
    alt: "TT",
    name: "TT",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-r8",
    src: "/addons/2eb32392.png",
    alt: "R8",
    name: "R8",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-rs5",
    src: "/addons/2eb32392.png",
    alt: "RS5",
    name: "RS5",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-rs3",
    src: "/addons/2eb32392.png",
    alt: "RS3",
    name: "RS3",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-q8",
    src: "/addons/2eb32392.png",
    alt: "Q8",
    name: "Q8",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/audi-e-tron",
    src: "/addons/2eb32392.png",
    alt: "e-tron",
    name: "e-tron",
  },
];

export const Mercedes = [
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-c-class",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-26-model-441.jpeg",
    alt: "C-Class",
    title: "C-Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-e-class",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-26-model-444.jpeg",
    alt: "E-Class",
    title: "E-Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-glc",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-26-model-586.jpeg",
    alt: "GLC",
    title: "GLC",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-cla-class",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-26-model-442.jpeg",
    alt: "CLA Class",
    title: "CLA Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-a-class",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-26-model-438.jpeg",
    alt: "A-Class",
    title: "A-Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-s-class",
    src: "https://gomechprod.blob.core.windows.net/gm-retail-app/thumbnails/brand-26-model-450.jpeg",
    alt: "S-Class",
    title: "S-Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-v-class",
    src: "/addons/2eb32392.png",
    alt: "V-Class",
    title: "V-Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-ml-class",
    src: "/addons/2eb32392.png",
    alt: "ML Class",
    title: "ML Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-b-class",
    src: "/addons/2eb32392.png",
    alt: "B-Class",
    title: "B-Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-gla-class",
    src: "/addons/2eb32392.png",
    alt: "GLA Class",
    title: "GLA Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-gle-class",
    src: "/addons/2eb32392.png",
    alt: "GLE Class",
    title: "GLE Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-sl-500-amg",
    src: "/addons/2eb32392.png",
    alt: "SL 500 AMG",
    title: "SL 500 AMG",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-amg-gt",
    src: "/addons/2eb32392.png",
    alt: "AMG GT",
    title: "AMG GT",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-g63-amgr",
    src: "/addons/2eb32392.png",
    alt: "G63 AMGr",
    title: "G63 AMGr",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-gl-class",
    src: "/addons/2eb32392.png",
    alt: "GL Class",
    title: "GL Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-slk-class",
    src: "/addons/2eb32392.png",
    alt: "SLK Class",
    title: "SLK Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-cls-class",
    src: "/addons/2eb32392.png",
    alt: "CLS Class",
    title: "CLS Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-gls",
    src: "/addons/2eb32392.png",
    alt: "GLS",
    title: "GLS",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-r-class",
    src: "/addons/2eb32392.png",
    alt: "R Class",
    title: "R Class",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-gle43-amg",
    src: "/addons/2eb32392.png",
    alt: "GLE43 AMG",
    title: "GLE43 AMG",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-eqc",
    src: "/addons/2eb32392.png",
    alt: "EQC",
    title: "EQC",
  },
  {
    href: "https://gomechanic.in/madurai/car-ac-repair/mercedes-eqs",
    src: "/addons/2eb32392.png",
    alt: "EQS",
    title: "EQS",
  },
];
